name: UnifiedMetrics
main: dev.cubxity.plugins.metrics.folia.bootstrap.UnifiedMetricsFoliaBootstrap
description: "Fully-featured metrics plugin for Minecraft servers (Folia)"
api-version: 1.20
author: Cubxity
version: ${version}
load: STARTUP
folia-supported: true
