{
 "title": "UnifiedMetrics 0.3.x / Prometheus",
 "description": "Fully-featured metrics collection agent for Minecraft servers.",
 "tags": [ "minecraft" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_players_count)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"^$job$\"})"
    }
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "world",
    "query": {
     "query": "query_result(minecraft_world_entities_count{instance=~\"$instance\",job=~\"$job\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Servers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_players_count{job=~\"^$job$\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-avg(process_start_time_seconds{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_entities_count{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(minecraft_tick_duration_seconds_count{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_cpu_load_ratio{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(minecraft_tick_duration_seconds_count{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])",
     "legendFormat": "tps: {{job}}"
    }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.75 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.99 quantile"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "players: {{job}}"
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"} - minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Folia: Region Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Lowest Region TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(minecraft_region_tps{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"})",
     "legendFormat": "Min TPS"
    }
   ]
  },
  {
   "title": "Avg Region TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_region_tps{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"})",
     "legendFormat": "Avg TPS"
    }
   ]
  },
  {
   "title": "Highest Region MSPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minecraft_region_mspt_seconds{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"}) * 1000",
     "legendFormat": "Max MSPT"
    }
   ]
  },
  {
   "title": "Avg Region MSPT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_region_mspt_seconds{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"}) * 1000",
     "legendFormat": "Avg MSPT"
    }
   ]
  },
  {
   "title": "Active Regions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_region_tps{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"})",
     "legendFormat": "Regions"
    }
   ]
  },
  {
   "title": "Region TPS (5s avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_region_tps{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"}",
     "legendFormat": "{{{{world}}}} [{{{{region}}}}]"
    }
   ]
  },
  {
   "title": "Region MSPT (5s avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "minecraft_region_mspt_seconds{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"} * 1000",
     "legendFormat": "{{{{world}}}} [{{{{region}}}}]"
    }
   ]
  },
  {
   "title": "All Regions (current snapshot)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "minecraft_region_tps{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"}"
    },
    {
     "expr": "minecraft_region_mspt_seconds{instance=~\"^$instance$\",job=~\"^$job$\",world=~\"$world\"} * 1000"
    }
   ]
  },
  { "title": "World [$world]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }, "repeat": "world" },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "chunks: {{job}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_world_entities_count{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "entities: {{job}}"
    },
    {
     "expr": "minecraft_world_players_count{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "players: {{job}}"
    }
   ]
  },
  { "title": "JVM: Computation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_load_ratio{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "cpu: {{job}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval])",
     "legendFormat": "cpu_seconds: {{job}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "threads: {{job}}"
    }
   ]
  },
  {
   "title": "Daemons",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "daemons: {{job}}"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_threads_started_total{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval",
     "legendFormat": "threads_started: {{job}}"
    }
   ]
  },
  { "title": "JVM: Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\",area=\"heap\"}",
     "legendFormat": "heap: {{job}}"
    }
   ]
  },
  {
   "title": "Nonheap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\",area=\"nonheap\"}",
     "legendFormat": "nonheap: {{job}}"
    }
   ]
  },
  {
   "title": "GC Duration (Mean)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gc) (jvm_gc_duration_seconds_sum{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_gc_duration_seconds_sum{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval)",
     "legendFormat": "gc_duration: {{gc}}"
    }
   ]
  },
  {
   "title": "GC Freed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(gc) (jvm_gc_freed_bytes_sum{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_gc_freed_bytes_sum{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval)",
     "legendFormat": "gc_freed: {{gc}}"
    }
   ]
  }
 ]
}